### ISSUE TITLE
Mapa mental Web 3.0 . Fernando Miguel López.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/mapa-mental-web-3-Ferch0419#1]
[Web 3.0 Mapa Mental_Fernando Miguel López.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-Ferch0419/files/8453822/Web.3.0.Mapa.Mental_Fernando.Miguel.Lopez.pdf)

**Comment by Yabin-2021** [comment]
Buen Trabajo 
20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
